version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    expose:
      - 8000
    volumes:
      - ./src:/src
    depends_on:
      - db
      - nginx

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eshop_db
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=123456Ab

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./src/static
        target: /src/static

      - type: bind
        source: ./src/media
        target: /src/media

volumes:
  postgres_data: