# Generated by Django 4.0 on 2022-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته بندی')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='تصویر محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول (تومان)')),
                ('sale_count', models.IntegerField(default=0, verbose_name='تعداد فروش')),
                ('product_count', models.IntegerField(verbose_name='تعداد محصول')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='products.Category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
